### ISSUE TITLE
Các bạn góp ý cho mình ở đây.

### ISSUE THREAD

**Issue by hts7117** [1712718-huynhthanhsang/LTKHDL_DACK#1]

**Comment by jekkyboy** [comment]
Chào bạn, mình muốn góp ý cái đồ thị bạn vẽ, mình nghĩ nên đặt tên cho trục hoành cũng như tiêu đề của đồ thị để nó rõ ràng hơn...

**Comment by hts7117** [comment]
> Chào bạn, mình muốn góp ý cái đồ thị bạn vẽ, mình nghĩ nên đặt tên cho trục hoành cũng như tiêu đề của đồ thị để nó rõ ràng hơn...

Mình sẽ thêm vào, bạn còn ý nào muons góp ý thêm không?

**Comment by jekkyboy** [comment]
Chào bạn, lại là mình đây (1712262)! Mình muốn góp ý thêm 3 thứ nữa cho bạn:
1. Phần lí do chọn đề tài mình nghĩ bạn nên để nó lên đầu.
2. Câu hỏi thứ 2 hơi sai chính tả: "hào nhoáng" không phải "hào nhoàng" =))))
3. Cuối cùng bạn nên có phần "Nhìn lại quá trình làm đồ án" bao gồm những khó khăn, học được những gì,... để có thể đầy đủ các phần theo hướng dẫn của Thầy

**Comment by hts7117** [comment]
mình tưởng nhìn lại quá trình làm đồ án sẽ ghi trong báo cáo chứ bạn
Cảm ơn bạn.

**Comment by jekkyboy** [comment]
nộp file .ipynb + data thôi bạn ơi, ko nộp báo cáo =)))

**Comment by hts7117** [comment]
OK ông
